# Generated by Django 5.2.1 on 2025-05-11 23:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chatbot', '0003_chatsession_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatsession',
            name='is_active',
        ),
    ]
